FROM nginx:alpine

# Sao chép tệp HTML tĩnh
COPY ./src/fallback-index.html /usr/share/nginx/html/index.html
COPY ./src/api-test-standalone.html /usr/share/nginx/html/api-test.html
COPY ./src/connection-test.html /usr/share/nginx/html/connection-test.html

# Cấu hình Nginx
COPY ./nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 4200

CMD ["nginx", "-g", "daemon off;"]
