FROM node:16-alpine as build

WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
RUN npm run build -- --configuration=production

FROM nginx:alpine
COPY --from=build /app/dist /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf

# Thêm file debug.html
COPY src/debug.html /usr/share/nginx/html/debug.html
COPY src/api-test.html /usr/share/nginx/html/api-test.html
COPY src/test.html /usr/share/nginx/html/test.html

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
