apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: incident-reporter
type: Opaque
data:
  # postgres (base64 encoded)
  POSTGRES_USER: cG9zdGdyZXM=
  # postgres (base64 encoded) 
  POSTGRES_PASSWORD: cG9zdGdyZXM=
  # sentinel (base64 encoded)
  POSTGRES_DB: c2VudGluZWw=
